os:
- osx
addons:
  chrome: stable
language: node_js
node_js:
- 8.15.1
notifications:
  email:
  - support@service-link.us
cache:
  directories:
  - node_modules
before_install:
- "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
- npm install -g greenkeeper-lockfile
install:
- npm install
before_script:
- greenkeeper-lockfile-update
script:
- npm run test
after_script:
- greenkeeper-lockfile-upload
env:
  global:
    secure: nRpjJ452JP3Ou8j/dzV1eotyc0ch1RPmZkBAKe221ZppUo9wuM2bStXnxJL9kUr9CFiPqIJVPjO/zIGBg1e49mezbKQCh422vGDeMHbDD3Oovlt5Xb4e55BFdzI+Xs5SUQIlM2+0kZ1ed8+VEZXxsh+b1GO6oq0zcyuQYQAH56n2RZcxGfCUUXDv2aDC/oCZJGy/yyYGAjSCqvVlSRl/JLqCAy7WWsYsfZdR+Fe8JBAQkMoWPzbNGttOTJAbk5O1G2e1pug53ImcS+1xTSWwz79JlO3gCGw/VRH2BZtrKJ/ZzD0V3rW3bNIDREahRBIBfzn91Pmyf31M8+Nz8q8FtMbCuXHpURwrxHRxFMTT01wXK684rY5NC4DgsBsqWQtexmqHV6qtEq9Kc3FniNBrPgyF2ti8OncKdkUEbSWgFu7SQ8UBkUjB4K9hbNGdo6QcmrMhKsjGKIv8K0rVRE1uPKeOLMPv8gV8K7Tve8c9KCalLE1b9UcgjvybbDXvnX7T5dx9RBgwcpagmLJUKLJjJXKqazayfpdiOFUB4HMhLQA9+p0iyhjehW+3Lw994uGYOvpP7A2jufpqqLD6CBCBulSKPOhCBX1fljwz1yiynaAcSjlXCefJl77zePx+R2WP42W1I+p4bMHUItxmFkCP1z12Zq5jMxflynFZxW2qwxo=
