os:
 - osx
addons:
  chrome: stable
language: node_js
node_js:
 - 8.9.0
cache:
  directories:
    - node_modules
install:
 - npm install
script:
 - npm run test
after_success:
 - npm run build
 - bash ./build.sh
