os:
 - osx
addons:
  chrome: stable
language: node_js
node_js:
 - 8.9.0
notifications:
  email:
    - support@service-link.us
cache:
  directories:
    - node_modules
install:
 - npm install
script:
 - npm run test
